// Code generated by protoc-gen-go.
// source: debug/ping.proto
// DO NOT EDIT!

/*
Package proto_debug is a generated protocol buffer package.

It is generated from these files:
	debug/ping.proto

It has these top-level messages:
	Ping
*/
package proto_debug

import proto "github.com/golang/protobuf/proto"
import math "math"
import proto_base "github.com/xjdrew/daisy/pb/base"
import proto_base1 "github.com/xjdrew/daisy/pb/base"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Ping struct {
	Ping             *string `protobuf:"bytes,1,opt,name=ping" json:"ping,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}

func (m *Ping) GetPing() string {
	if m != nil && m.Ping != nil {
		return *m.Ping
	}
	return ""
}

type Ping_Response struct {
	Pong             *string           `protobuf:"bytes,1,opt,name=pong" json:"pong,omitempty"`
	Error            *proto_base.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Pack             *proto_base1.Pack `protobuf:"bytes,3,opt,name=pack" json:"pack,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Ping_Response) Reset()         { *m = Ping_Response{} }
func (m *Ping_Response) String() string { return proto.CompactTextString(m) }
func (*Ping_Response) ProtoMessage()    {}

func (m *Ping_Response) GetPong() string {
	if m != nil && m.Pong != nil {
		return *m.Pong
	}
	return ""
}

func (m *Ping_Response) GetError() *proto_base.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Ping_Response) GetPack() *proto_base1.Pack {
	if m != nil {
		return m.Pack
	}
	return nil
}

func init() {
}
